apiVersion: v1
kind: Deployment
metadata:
  name: sql_server_deployment
  labels:
    app: sql_server
spec:
  replicas: 1
  selector:
  matchLabels:
    app: sql_server
  template:
    metadata:
      labels:
        sql_server
    spec:
      containers:
      - name: sql_server
        image: mcr.microsoft.com/mssql/server
        # resources:
        #   limits:
        #     memory: 100Mi
        #     cpu: 100m
        #   requests:
        #     memory: 100Mi
        #     cpu: 100m
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql_server_secret
              key: MSSQL_SA_PASSWORD
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - 'key': 'nautilus.io/csu-tide'
                'operator': 'In'
                'values': ["true"]
      tolerations:
        - effect: NoSchedule
          key: nautilus.io/csu-tidea
          operator: Exists
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: sql_server_pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sql_server_service
spec:
  selector:
    app: sql_server
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433