apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server-deployment
  labels:
    app: sql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
      - name: sql-server
        image: mcr.microsoft.com/mssql/server
        resources:
          limits:
            memory: 2G
            cpu: 2000m
          requests:
            memory: 2G
            cpu: 2000m
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-server-secret
              key: MSSQL_SA_PASSWORD
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nautilus.io/csu-tide
                operator: In
                values: ["true"]
      tolerations:
        - effect: NoSchedule
          key: nautilus.io/csu-tide
          operator: Exists
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: sql-server-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sql-server-service
spec:
  selector:
    app: sql-server
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433