apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-server-pvc
spec:
  storageClassName: rook-ceph-block-tide
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi